server:
  port: 4444
  
spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
      - id: fotbalist-service
        uri:
          lb://fotbalist
          http://fotbalist/
          http://fotbalist:2222/
        predicates:
        - Path=/fotbalist/**
        filters:
        - name: CircuitBreaker
          args:
            name: fotbalist-service
            fallbackuri: forward:/fotbalistServiceFallBack #trebe sa fie invers, caci daca pica stucent service to asta ne apare ca picat
      - id: echipa-service
        uri:
          lb://echipa-service  #e optional cred, e de la ribbon
        predicates:
        - Path=/echipa/** 
        filters:
        - name: CircuitBreaker
          args:
            name: echipa-service
            fallbackuri: forward:/echipaServiceFallBack
            
            
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka/
  instance:
    prefer-ip-address: true
